### ISSUE TITLE
Profile Pic is not showing

### ISSUE THREAD

**Issue by Satyamkan10** [Satyamkan10/myportfolio#1]
<img width="1117" alt="image" src="https://github.com/Satyamkan10/myportfolio/assets/109055716/72d3458a-4dd7-4f27-80e2-8ff0a5203aa5">

**Comment by Satyamkan10** [comment]
in local it is working properly but when I host this with use of GitHub then it show this error

**Comment by SanjeevKD** [comment]
Have you tried deploying it on some different cloud providers like Azure,  AWS.
